# Generated by Django 5.2.8 on 2025-11-30 02:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WarsawBoundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Warszawa", max_length=100)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name_plural": "Warsaw Boundaries",
            },
        ),
        migrations.CreateModel(
            name="GridCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grid_id", models.CharField(max_length=20, unique=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("district", models.CharField(blank=True, max_length=100)),
                ("sighting_count", models.PositiveIntegerField(default=0)),
                ("last_sighting_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["district"], name="sightings_g_distric_9fa3e3_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Sighting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Lokalizacja zgłoszenia (WGS84)", srid=4326
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Data i czas obserwacji",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje na weryfikację"),
                            ("verified", "Zweryfikowane"),
                            ("rejected", "Odrzucone"),
                            ("duplicate", "Duplikat"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "boar_count",
                    models.CharField(
                        choices=[
                            ("1", "Pojedynczy"),
                            ("2-3", "2-3 osobniki"),
                            ("4-10", "4-10 osobników"),
                            ("10+", "Ponad 10"),
                        ],
                        default="1",
                        help_text="Szacunkowa liczba dzików",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Opcjonalny opis", max_length=1000
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        help_text="HMAC-SHA256 hash of IP for anti-spam",
                        max_length=64,
                    ),
                ),
                (
                    "grid_cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sightings",
                        to="sightings.gridcell",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "observed_at"],
                        name="sightings_s_status_3e76cf_idx",
                    )
                ],
            },
        ),
    ]
