# Generated by Django 5.2.8 on 2025-11-30 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sightings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("task_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("result_summary", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("parameters", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("gwr", "Geographically Weighted Regression"),
                            ("rf", "Random Forest"),
                            ("ensemble", "Ensemble (GWR + RF)"),
                        ],
                        default="ensemble",
                        max_length=20,
                    ),
                ),
                ("model_version", models.CharField(max_length=50)),
                (
                    "prediction_value",
                    models.FloatField(
                        help_text="Predicted encounter probability (0-1)"
                    ),
                ),
                ("confidence_lower", models.FloatField(blank=True, null=True)),
                ("confidence_upper", models.FloatField(blank=True, null=True)),
                (
                    "prediction_date",
                    models.DateField(help_text="Date this prediction is valid for"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "local_r_squared",
                    models.FloatField(
                        blank=True, help_text="Local R² from GWR", null=True
                    ),
                ),
                (
                    "bandwidth",
                    models.FloatField(
                        blank=True, help_text="GWR bandwidth in meters", null=True
                    ),
                ),
                (
                    "grid_cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="sightings.gridcell",
                    ),
                ),
            ],
            options={
                "ordering": ["-prediction_date", "grid_cell"],
                "indexes": [
                    models.Index(
                        fields=["prediction_date", "model_type"],
                        name="analytics_m_predict_b58241_idx",
                    ),
                    models.Index(
                        fields=["grid_cell", "prediction_date"],
                        name="analytics_m_grid_ce_b20b8b_idx",
                    ),
                ],
                "unique_together": {("grid_cell", "model_type", "prediction_date")},
            },
        ),
    ]
