# Generated by Django 5.0.1 - Manual migration for ParameterConfiguration

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_bayesianresult_priorconfig_trajectory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Configuration profile name (e.g., 'production', 'quick_preview')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Only one configuration can be active"
                    ),
                ),
                (
                    "bayesian_kappa",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Prior concentration parameter kappa (2-50, default 10). Higher = stronger priors.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(2.0),
                            django.core.validators.MaxValueValidator(50.0),
                        ],
                    ),
                ),
                (
                    "persistence_rho_mean",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.82,
                        help_text="Expected persistence rho (0-0.99). From ARI via STS.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(0.99),
                        ],
                    ),
                ),
                (
                    "diffusion_delta_mean",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.20,
                        help_text="Expected diffusion delta (0-0.99). From H_rel via ETA.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(0.99),
                        ],
                    ),
                ),
                (
                    "mcmc_iterations",
                    models.IntegerField(
                        default=2000,
                        help_text="Total MCMC iterations per chain",
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "mcmc_warmup",
                    models.IntegerField(
                        default=1000,
                        help_text="Warmup iterations (must be < iterations)",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                (
                    "mcmc_chains",
                    models.IntegerField(
                        default=4,
                        help_text="Number of MCMC chains (4 recommended for publication)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "mcmc_adapt_delta",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.95,
                        help_text="Stan adapt_delta parameter (higher = fewer divergences)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.8),
                            django.core.validators.MaxValueValidator(0.999),
                        ],
                    ),
                ),
                (
                    "mcmc_seed",
                    models.IntegerField(
                        default=42, help_text="Random seed for reproducibility"
                    ),
                ),
                (
                    "trajectory_count",
                    models.IntegerField(
                        default=1000,
                        help_text="Number of trajectories to generate",
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "bayesian_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable Bayesian SSM layer"
                    ),
                ),
                (
                    "trajectories_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable trajectory generation"
                    ),
                ),
                (
                    "weight_rf",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.25,
                        help_text="Random Forest weight in ensemble",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "weight_gwr",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.35,
                        help_text="GWR weight in ensemble",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "weight_eta",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.20,
                        help_text="ETA weight in ensemble",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "weight_bayesian",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.20,
                        help_text="Bayesian SSM weight in ensemble",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parameter Configuration",
                "verbose_name_plural": "Parameter Configurations",
                "db_table": "analytics_parameter_configuration",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
    ]
