import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_partial_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Unique name for this configuration profile", max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=False, help_text="Only one configuration can be active at a time")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("geometry_type", models.CharField(choices=[("voronoi", "Voronoi tessellation"), ("grid_500", "Regular grid 500m")], default="voronoi", help_text="Spatial unit type for analysis", max_length=20)),
                ("population_method", models.CharField(choices=[("spatial_join", "Area-weighted spatial join (GUS 500m)"), ("points", "Point-in-polygon count"), ("centroid", "Centroid lookup")], default="spatial_join", help_text="How to assign population to spatial units", max_length=20)),
                ("y_formula", models.CharField(choices=[("count_pop", "sighting_count / population"), ("inv_pop", "1 / (population + 1)"), ("log_pop", "log(population + 1)"), ("log_count", "log(sighting_count + 1)"), ("binary", "binary (0/1 sighting presence)")], default="log_pop", help_text="Dependent variable formula", max_length=20)),
                ("w_method", models.CharField(choices=[("knn_aic", "KNN with AIC selection"), ("contiguity", "Queen contiguity"), ("tessw", "tessW (spatialWarsaw)")], default="knn_aic", help_text="Spatial weight matrix construction method", max_length=20)),
                ("k_range_min", models.PositiveIntegerField(default=2, help_text="Minimum k for KNN range search", validators=[django.core.validators.MinValueValidator(1)])),
                ("k_range_max", models.PositiveIntegerField(default=50, help_text="Maximum k for KNN range search", validators=[django.core.validators.MinValueValidator(2)])),
                ("model_type", models.CharField(choices=[("auto", "Auto (select by LM tests)"), ("sar", "SAR (Spatial Lag)"), ("sem", "SEM (Spatial Error)"), ("sdm", "SDM (Spatial Durbin)"), ("probit", "Spatial Probit"), ("logit", "Spatial Logit")], default="auto", help_text="Spatial model type (auto = selected by LM tests)", max_length=20)),
                ("active_predictors", models.JSONField(default=list, help_text="List of active OSM predictor names")),
                ("run_moran", models.BooleanField(default=True, help_text="Run Moran's I test for spatial autocorrelation")),
                ("run_lm_tests", models.BooleanField(default=True, help_text="Run LM lag/error tests for model selection")),
                ("run_lisa", models.BooleanField(default=False, help_text="Run Local Indicators of Spatial Association")),
                ("run_eta", models.BooleanField(default=False, help_text="Run ETA (Entropy-Tessellation-Agglomeration)")),
                ("vif_threshold", models.FloatField(default=5.0, help_text="VIF threshold for multicollinearity check", validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)])),
                ("alpha", models.FloatField(default=0.05, help_text="Significance level for statistical tests", validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(0.5)])),
                ("seed", models.PositiveIntegerField(default=42, help_text="Random seed for reproducibility")),
                ("date_from", models.DateField(blank=True, help_text="Include sightings from this date (inclusive)", null=True)),
                ("date_to", models.DateField(blank=True, help_text="Include sightings up to this date (inclusive)", null=True)),
                ("use_regime_model", models.BooleanField(default=False, help_text="Use regime model (binary forest/urban)")),
                ("regime_type", models.CharField(choices=[("none", "Brak (jeden globalny model)"), ("trinary", "Trinary (las/miasto/mixed)")], default="none", help_text="Type of regime classification", max_length=20)),
                ("regime_threshold", models.FloatField(default=0.3, help_text="Forest cover threshold for regime classification (0-1)", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ("regime_threshold_urban", models.FloatField(default=0.15, help_text="Building density threshold for urban regime (0-1)", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                "verbose_name": "Research Config",
                "verbose_name_plural": "Research Configs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("config_snapshot", models.JSONField(help_text="Frozen copy of config at the moment of run start")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("success", "Success"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("n_sightings", models.PositiveIntegerField(help_text="Number of sightings included in this run")),
                ("n_cells", models.PositiveIntegerField(blank=True, help_text="Number of spatial units generated", null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("config", models.ForeignKey(blank=True, help_text="Source config (may be null if config deleted)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="runs", to="analytics.researchconfig")),
            ],
            options={
                "verbose_name": "Research Run",
                "verbose_name_plural": "Research Runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchDiagnostics",
            fields=[
                ("run", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="diagnostics", serialize=False, to="analytics.researchrun")),
                ("moran_i", models.FloatField(blank=True, help_text="Moran's I statistic", null=True)),
                ("moran_expected", models.FloatField(blank=True, help_text="Expected Moran's I under H0", null=True)),
                ("moran_variance", models.FloatField(blank=True, help_text="Variance of Moran's I", null=True)),
                ("moran_z", models.FloatField(blank=True, help_text="Z-score", null=True)),
                ("moran_p", models.FloatField(blank=True, help_text="p-value", null=True)),
                ("lm_lag_stat", models.FloatField(blank=True, help_text="LM Lag test statistic", null=True)),
                ("lm_lag_p", models.FloatField(blank=True, help_text="LM Lag p-value", null=True)),
                ("lm_error_stat", models.FloatField(blank=True, help_text="LM Error test statistic", null=True)),
                ("lm_error_p", models.FloatField(blank=True, help_text="LM Error p-value", null=True)),
                ("rlm_lag_stat", models.FloatField(blank=True, help_text="Robust LM Lag statistic", null=True)),
                ("rlm_lag_p", models.FloatField(blank=True, help_text="Robust LM Lag p-value", null=True)),
                ("rlm_error_stat", models.FloatField(blank=True, help_text="Robust LM Error statistic", null=True)),
                ("rlm_error_p", models.FloatField(blank=True, help_text="Robust LM Error p-value", null=True)),
                ("model_selected", models.CharField(blank=True, default="", help_text="Model actually selected (sar/sem/sdm/probit/logit)", max_length=20)),
                ("aic", models.FloatField(blank=True, help_text="Akaike Information Criterion", null=True)),
                ("log_likelihood", models.FloatField(blank=True, null=True)),
                ("coefficients", models.JSONField(blank=True, help_text="Dict of predictor coefficients {name: {estimate, std_error, z, p}}", null=True)),
                ("r_squared", models.FloatField(blank=True, help_text="Pseudo R-squared", null=True)),
                ("rho", models.FloatField(blank=True, help_text="SAR spatial lag parameter rho", null=True)),
                ("lambda_param", models.FloatField(blank=True, help_text="SEM spatial error parameter lambda", null=True)),
                ("lisa_hh_count", models.PositiveIntegerField(blank=True, help_text="High-High clusters", null=True)),
                ("lisa_ll_count", models.PositiveIntegerField(blank=True, help_text="Low-Low clusters", null=True)),
                ("lisa_hl_count", models.PositiveIntegerField(blank=True, help_text="High-Low outliers", null=True)),
                ("lisa_lh_count", models.PositiveIntegerField(blank=True, help_text="Low-High outliers", null=True)),
                ("lisa_ns_count", models.PositiveIntegerField(blank=True, help_text="Not significant", null=True)),
                ("vif_results", models.JSONField(blank=True, help_text="VIF per predictor {name: vif_value}", null=True)),
                ("predictors_dropped", models.JSONField(default=list, help_text="Predictors dropped due to VIF > threshold")),
                ("eta_h_emp", models.FloatField(blank=True, help_text="Empirical Shannon entropy: H = -Σ(s_i × ln(s_i))", null=True)),
                ("eta_h_max", models.FloatField(blank=True, help_text="Maximum entropy: H_max = ln(n)", null=True)),
                ("eta_h_rel", models.FloatField(blank=True, help_text="ETA (relative entropy): H_rel = H / H_max. Range [0,1]. ~1=uniform, <0.8=agglomeration", null=True)),
                ("k_selected", models.PositiveIntegerField(blank=True, help_text="Selected optimal k (for knn_aic method)", null=True)),
                ("mean_neighbors", models.FloatField(blank=True, help_text="Average number of neighbors per cell in W matrix", null=True)),
                ("impacts", models.JSONField(blank=True, help_text="Spatial impacts: {direct: {...}, indirect: {...}, total: {...}} (SAR/SDM only)", null=True)),
            ],
            options={
                "verbose_name": "Research Diagnostics",
                "verbose_name_plural": "Research Diagnostics",
            },
        ),
        migrations.CreateModel(
            name="ResearchStepLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_name", models.CharField(help_text="Human-readable step name (e.g. '01_generate_voronoi.R')", max_length=100)),
                ("step_order", models.PositiveIntegerField(help_text="Execution order (1-based)")),
                ("step_type", models.CharField(choices=[("R", "R script"), ("Python", "Python"), ("SQL", "SQL query")], max_length=10)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("exit_code", models.IntegerField(blank=True, help_text="Process exit code (0=success, 3=fallback, 137=OOM)", null=True)),
                ("status", models.CharField(choices=[("running", "Running"), ("success", "Success"), ("failed", "Failed"), ("skipped", "Skipped")], default="running", max_length=10)),
                ("input_params", models.JSONField(default=dict, help_text="Parameters passed to this step")),
                ("output_stats", models.JSONField(blank=True, help_text="Statistics returned by this step", null=True)),
                ("stdout", models.TextField(blank=True, default="")),
                ("stderr", models.TextField(blank=True, default="")),
                ("errors", models.JSONField(default=list, help_text="List of error messages")),
                ("warnings", models.JSONField(default=list, help_text="List of warning messages")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="analytics.researchrun")),
            ],
            options={
                "verbose_name": "Research Step Log",
                "verbose_name_plural": "Research Step Logs",
                "ordering": ["run", "step_order"],
                "unique_together": {("run", "step_order")},
            },
        ),
    ]
