# Generated by Django 5.2.10 on 2026-06-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_research_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchconfig',
            name='y_formula',
            field=models.CharField(choices=[('log_intensity', 'log((sighting_count + 1) / area_km2) - risk signal (default)'), ('count_pop', 'sighting_count / population'), ('inv_pop', '1 / (population + 1)'), ('log_pop', 'log(population + 1)'), ('log_count', 'log(sighting_count + 1)'), ('binary', 'binary (0/1 sighting presence)')], default='log_intensity', help_text='Dependent variable formula', max_length=20),
        ),
    ]
